# EdgeLake Nodes Configuration
# Define EdgeLake nodes that the MCP server can connect to

version: "1.0"

# Node definitions
nodes:
  - name: "local"
    description: "Local EdgeLake node"
    host: "127.0.0.1"
    port: 32049
    is_default: true
    
  - name: "production-query"
    description: "Production Query Node"
    host: "10.0.0.25"
    port: 32049
    is_default: false
    
  - name: "production-operator-1"
    description: "Production Operator Node 1"
    host: "10.0.0.26"
    port: 32049
    is_default: false

# Client configuration
client:
  # Allow users to specify custom nodes at runtime
  allow_custom_nodes: true
  
  # Custom node hint for MCP clients
  custom_node_hint: |
    You can specify a custom EdgeLake node by providing 'node_host' and 'node_port' parameters.
    Example: node_host="192.168.1.100" and node_port=32049
  
  # Default timeout for requests (seconds)
  request_timeout: 20
  
  # Maximum concurrent workers for threaded execution
  max_workers: 10
  
  # Connection retry settings
  retry:
    max_attempts: 3
    backoff_factor: 2
    timeout_multiplier: 1.5

# Environment variable overrides
# These can be set to override configuration at runtime
env_overrides:
  default_node: "EDGELAKE_DEFAULT_NODE"  # Name of default node
  host: "EDGELAKE_HOST"                   # Override host
  port: "EDGELAKE_PORT"                   # Override port
  timeout: "EDGELAKE_TIMEOUT"             # Override timeout
