# EdgeLake MCP Tools Configuration
# This file defines the MCP tools dynamically based on EdgeLake commands from member_cmd.py

version: "1.0"

tools:
  # Database Discovery Tools
  - name: list_databases
    description: "List all available databases in EdgeLake. Use this to discover what databases are available before querying."
    edgelake_command:
      type: "blockchain_query"
      query_type: "get_all_databases"
    input_schema:
      type: object
      properties: {}
      required: []

  - name: list_tables
    description: "List all tables in a specific database. Use this to discover what tables are available in a database before querying."
    edgelake_command:
      type: "blockchain_query"
      query_type: "get_tables_for_database"
      parameters:
        database: "{database}"
    input_schema:
      type: object
      properties:
        database:
          type: string
          description: "Database name to list tables from"
      required: ["database"]
  
  - name: get_schema
    description: "Get the schema (column definitions) for a specific table. Use this to understand what columns are available before querying."
    edgelake_command:
      type: "get"
      method: "columns"
      template: 'get columns where dbms="{database}" and table="{table}" and format=json'
    input_schema:
      type: object
      properties:
        database:
          type: string
          description: "Database name"
        table:
          type: string
          description: "Table name"
      required: ["database", "table"]
  
  # Query Execution Tool
  - name: query
    description: "Execute distributed SQL query across EdgeLake network with advanced filtering, grouping, and ordering options"
    edgelake_command:
      type: "sql_query"
      query_type: "network"
    input_schema:
      type: object
      properties:
        database:
          type: string
          description: "Database name to query"
        table:
          type: string
          description: "Table name to query"
        select:
          type: array
          items:
            type: string
          description: "Columns to select (default: all columns with *)"
          default: ["*"]
        where:
          type: string
          description: "WHERE clause conditions (e.g., 'is_active = true AND age > 18'). Supports AND/OR operators"
        group_by:
          type: array
          items:
            type: string
          description: "Columns to group by (required when using aggregations with non-aggregated columns)"
        order_by:
          type: array
          items:
            type: object
            properties:
              column:
                type: string
              direction:
                type: string
                enum: ["ASC", "DESC"]
                default: "ASC"
            required: ["column"]
          description: "Order results by columns with optional ASC/DESC direction"
        limit:
          type: integer
          description: "Maximum number of rows to return"
          minimum: 1
          default: 100
        format:
          type: string
          enum: ["json", "table"]
          description: "Output format"
          default: "json"
      required: ["database", "table"]
  
  # Node Status Tool
  - name: node_status
    description: "Get the status and health information of the EdgeLake node"
    edgelake_command:
      type: "node_query"
      query_type: "get_node_status"
    input_schema:
      type: object
      properties: {}
      required: []
  
  # Server Info Tool
  - name: server_info
    description: "Get EdgeLake MCP Server version and configuration information"
    edgelake_command:
      type: "internal"
      method: "server_info"
    input_schema:
      type: object
      properties: {}
      required: []
  

# Response Parsers
# These define how to parse EdgeLake responses into MCP-compatible formats
response_parsers:
  extract_databases:
    type: "blockchain_table"
    extract: "unique_databases"
    from_column: 0
    
  extract_tables:
    type: "blockchain_table"
    extract: "tables_for_database"
    from_columns: [0, 1]  # database, table
    filter_column: 0
